import { Prisma } from "@prisma/client";

type ResolvableQuestion = Omit<
  Prisma.PastQuestionCreateManyInput,
  "subjectId" | "topicId"
> & {
  subjectName: string;
  topicTitle: string;
};

const S = "WAEC Biology";
const PH = "placeholder";

// ── 1. Cell Biology and Living Things ───────────────────────────────────────
const cellBiology: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Cell Biology and Living Things",
    questionText: "Which organelle is responsible for the production of ATP through cellular respiration?",
    answerText: "Mitochondria",
    explanationText: "Mitochondria are the powerhouses of the cell; they generate ATP via aerobic respiration in their inner membranes.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Cell Biology and Living Things",
    questionText: "The process by which water molecules move across a selectively permeable membrane from a dilute solution to a more concentrated solution is called",
    answerText: "Osmosis",
    explanationText: "Osmosis is the passive movement of water molecules down a water potential gradient across a selectively permeable membrane.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Cell Biology and Living Things",
    questionText: "Which kingdom contains organisms that are unicellular, prokaryotic, and lack a true nucleus?",
    answerText: "Monera",
    explanationText: "The kingdom Monera (Prokaryota) includes bacteria and cyanobacteria, which are unicellular organisms without a membrane-bound nucleus.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Cell Biology and Living Things",
    questionText: "A group of similar cells working together to perform a specific function is called a",
    answerText: "Tissue",
    explanationText: "A tissue is an organised group of similar cells that carry out a common function. Several tissues form an organ.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Cell Biology and Living Things",
    questionText: "Which organelle is the site of protein synthesis in a cell?",
    answerText: "Ribosome",
    explanationText: "Ribosomes translate mRNA sequences into polypeptide chains. They are found free in the cytoplasm or attached to the rough endoplasmic reticulum.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Cell Biology and Living Things",
    questionText: "The cell wall of plant cells is made mainly of which polysaccharide?",
    answerText: "Cellulose",
    explanationText: "Cellulose fibres in the cell wall give plant cells mechanical strength and a fixed shape, unlike animal cells which lack a cell wall.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Cell Biology and Living Things",
    questionText: "Active transport differs from diffusion in that active transport",
    answerText: "Requires metabolic energy (ATP) to move substances against a concentration gradient",
    explanationText: "Active transport uses carrier proteins and ATP to move substances from low to high concentration, against the concentration gradient.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Cell Biology and Living Things",
    questionText: "Which of the following is found in plant cells but NOT in animal cells?",
    answerText: "Chloroplast",
    explanationText: "Chloroplasts contain chlorophyll and are the site of photosynthesis. They are found only in plant cells and other photosynthetic organisms.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Cell Biology and Living Things",
    questionText: "The movement of molecules from a region of higher concentration to lower concentration without energy expenditure is called",
    answerText: "Diffusion",
    explanationText: "Diffusion is the passive movement of particles down a concentration gradient and requires no metabolic energy.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Cell Biology and Living Things",
    questionText: "In the biological hierarchy of organisation, which level is directly above the organ level?",
    answerText: "Organ system",
    explanationText: "The hierarchy runs: cell → tissue → organ → organ system → organism. An organ system is a group of organs working together for a major body function.",
    difficulty: 2,
    source: PH,
  },
];

// ── 2. Nutrition in Plants and Animals ──────────────────────────────────────
const nutrition: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Nutrition in Plants and Animals",
    questionText: "Photosynthesis occurs mainly in which organelle of plant cells?",
    answerText: "Chloroplast",
    explanationText: "The chloroplast contains chlorophyll which absorbs light energy; both the light-dependent and light-independent reactions of photosynthesis take place here.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Nutrition in Plants and Animals",
    questionText: "The overall equation for photosynthesis is: 6CO₂ + 6H₂O → C₆H₁₂O₆ + ___",
    answerText: "6O₂",
    explanationText: "Oxygen is released as a by-product when water molecules are split during the light-dependent reactions (photolysis).",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Nutrition in Plants and Animals",
    questionText: "Which mineral element is essential for the synthesis of chlorophyll in plants?",
    answerText: "Magnesium",
    explanationText: "Magnesium is the central atom in the chlorophyll molecule. Deficiency causes chlorosis (yellowing of leaves).",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Nutrition in Plants and Animals",
    questionText: "An organism that manufactures its own food from inorganic substances using light or chemical energy is called",
    answerText: "Autotroph",
    explanationText: "Autotrophs (e.g. green plants, algae, some bacteria) synthesise organic compounds from CO₂ and water using photosynthesis or chemosynthesis.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Nutrition in Plants and Animals",
    questionText: "Which enzyme in the mouth begins the chemical digestion of starch?",
    answerText: "Salivary amylase",
    explanationText: "Salivary amylase (ptyalin) is secreted by the salivary glands and catalyses the hydrolysis of starch into maltose in the mouth.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Nutrition in Plants and Animals",
    questionText: "Proteins are digested into amino acids by enzymes called",
    answerText: "Proteases",
    explanationText: "Proteases (e.g. pepsin, trypsin, peptidases) hydrolyse peptide bonds in proteins, breaking them down into amino acids.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Nutrition in Plants and Animals",
    questionText: "A balanced diet must include all of the following EXCEPT",
    answerText: "Antibiotics",
    explanationText: "A balanced diet contains carbohydrates, proteins, fats, vitamins, minerals, water, and fibre. Antibiotics are medicines, not dietary components.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Nutrition in Plants and Animals",
    questionText: "The primary function of carbohydrates in the diet is to provide",
    answerText: "Energy",
    explanationText: "Carbohydrates are the main energy substrate. They are broken down to glucose, which is oxidised in respiration to release ATP.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Nutrition in Plants and Animals",
    questionText: "Which nutrient class is most important for growth and repair of body tissues?",
    answerText: "Proteins",
    explanationText: "Proteins supply amino acids used to build and repair body structures, produce enzymes, hormones, and antibodies.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Nutrition in Plants and Animals",
    questionText: "The mode of nutrition exhibited by green plants is described as",
    answerText: "Holophytic (autotrophic) nutrition",
    explanationText: "Green plants use holophytic nutrition: they synthesise organic food from inorganic raw materials using light energy via photosynthesis.",
    difficulty: 2,
    source: PH,
  },
];

// ── 3. Respiration and Gaseous Exchange ──────────────────────────────────────
const respiration: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Respiration and Gaseous Exchange",
    questionText: "Aerobic respiration produces a maximum of how many ATP molecules per molecule of glucose?",
    answerText: "38 ATP",
    explanationText: "Aerobic respiration of one glucose molecule yields approximately 38 ATP via glycolysis, the Krebs cycle, and oxidative phosphorylation.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Respiration and Gaseous Exchange",
    questionText: "During anaerobic respiration in humans, glucose is incompletely broken down to produce lactic acid and",
    answerText: "ATP",
    explanationText: "Anaerobic respiration in muscle cells converts glucose to lactic acid, yielding only 2 ATP per glucose — much less than aerobic respiration.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Respiration and Gaseous Exchange",
    questionText: "The respiratory surface in fish through which gaseous exchange occurs is the",
    answerText: "Gill lamellae",
    explanationText: "Fish extract dissolved oxygen from water through the large surface area of the gill lamellae, which are richly supplied with blood capillaries.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Respiration and Gaseous Exchange",
    questionText: "Gaseous exchange in terrestrial plants occurs mainly through tiny pores called",
    answerText: "Stomata",
    explanationText: "Stomata are pores on leaf surfaces, each flanked by guard cells, through which CO₂ enters for photosynthesis and O₂ and water vapour exit.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Respiration and Gaseous Exchange",
    questionText: "In mammals, the diaphragm and intercostal muscles work together to cause",
    answerText: "Ventilation of the lungs",
    explanationText: "Contraction of the diaphragm and external intercostal muscles increases thoracic volume, decreasing pressure and drawing air into the lungs (inhalation).",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Respiration and Gaseous Exchange",
    questionText: "Anaerobic respiration in yeast produces ethanol and",
    answerText: "Carbon dioxide",
    explanationText: "Yeast fermentation: C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂. This is the basis of brewing and bread-making.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Respiration and Gaseous Exchange",
    questionText: "The first stage of aerobic respiration, which occurs in the cytoplasm, is called",
    answerText: "Glycolysis",
    explanationText: "Glycolysis breaks one glucose molecule (6C) into two pyruvate molecules (3C each), producing 2 ATP and 2 NADH in the cytoplasm.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Respiration and Gaseous Exchange",
    questionText: "Which gas is released as a waste product of aerobic respiration?",
    answerText: "Carbon dioxide",
    explanationText: "Aerobic respiration: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy. Carbon dioxide is expelled through the lungs (or stomata in plants).",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Respiration and Gaseous Exchange",
    questionText: "The respiratory organ in adult amphibians (e.g. frogs) includes all of the following EXCEPT",
    answerText: "Gills only",
    explanationText: "Adult frogs respire using lungs, moist skin, and the lining of the mouth. Gills are used only in tadpole (larval) stages, not exclusively in adults.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Respiration and Gaseous Exchange",
    questionText: "The oxygen debt incurred during strenuous exercise is repaid by",
    answerText: "Oxidising accumulated lactic acid back to carbon dioxide and water",
    explanationText: "After exercise, extra oxygen is used to convert lactic acid into pyruvate, then fully oxidise it to CO₂ and H₂O, repaying the oxygen debt.",
    difficulty: 3,
    source: PH,
  },
];

// ── 4. Transport Systems ─────────────────────────────────────────────────────
const transport: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Transport Systems",
    questionText: "The main function of red blood cells (erythrocytes) is to",
    answerText: "Transport oxygen",
    explanationText: "Red blood cells contain haemoglobin, which reversibly binds oxygen in the lungs and releases it to respiring tissues.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Transport Systems",
    questionText: "Which blood vessel carries oxygenated blood away from the heart to the body tissues?",
    answerText: "Aorta",
    explanationText: "The aorta is the largest artery; it carries oxygenated blood from the left ventricle to the systemic circulation.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Transport Systems",
    questionText: "Water and mineral salts are absorbed from soil into the root through cells that have long extensions called",
    answerText: "Root hair cells",
    explanationText: "Root hair cells greatly increase the surface area for absorption of water (by osmosis) and mineral ions (by active transport) from the soil.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Transport Systems",
    questionText: "The tissue in plants responsible for transporting water and dissolved minerals upward from roots to leaves is the",
    answerText: "Xylem",
    explanationText: "Xylem vessels are dead, hollow tubes that conduct water and mineral salts upward from roots to stems and leaves via transpiration pull.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Transport Systems",
    questionText: "In the cardiac cycle, the phase during which the ventricles contract and pump blood is called",
    answerText: "Ventricular systole",
    explanationText: "During ventricular systole, the ventricles contract, closing the atrioventricular valves and opening the semilunar valves to eject blood.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Transport Systems",
    questionText: "The liquid component of blood, which transports dissolved substances, is called",
    answerText: "Blood plasma",
    explanationText: "Blood plasma (approximately 55% of blood volume) is a yellowish liquid that carries nutrients, hormones, waste products, and clotting proteins.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Transport Systems",
    questionText: "The tissue in plants responsible for transporting dissolved organic food (sugars) from leaves to other parts of the plant is the",
    answerText: "Phloem",
    explanationText: "Phloem conducts photosynthates (mainly sucrose) in both directions from sources (leaves) to sinks (roots, fruits, growing regions).",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Transport Systems",
    questionText: "The force that drives water up through the xylem in tall plants is mainly due to",
    answerText: "Transpiration pull (cohesion-tension)",
    explanationText: "As water evaporates from leaves (transpiration), it creates a tension that pulls water up through the continuous column of xylem vessels by cohesion.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Transport Systems",
    questionText: "Which chamber of the heart pumps deoxygenated blood to the lungs?",
    answerText: "Right ventricle",
    explanationText: "The right ventricle contracts to push deoxygenated blood through the pulmonary artery to the lungs for oxygenation.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Transport Systems",
    questionText: "Lymph is a fluid that is drained from body tissues into lymph capillaries and eventually returned to the",
    answerText: "Blood circulatory system",
    explanationText: "Lymph vessels collect excess tissue fluid and return it to the bloodstream via the thoracic duct and right lymphatic duct, which drain into subclavian veins.",
    difficulty: 2,
    source: PH,
  },
];

// ── 5. Excretion and Homeostasis ─────────────────────────────────────────────
const excretion: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Excretion and Homeostasis",
    questionText: "The main nitrogenous excretory product in mammals is",
    answerText: "Urea",
    explanationText: "Mammals convert toxic ammonia (from amino acid deamination) to less-toxic urea in the liver; urea is then excreted by the kidneys in urine.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Excretion and Homeostasis",
    questionText: "The functional unit of the kidney responsible for urine formation is the",
    answerText: "Nephron",
    explanationText: "Each kidney contains about one million nephrons. Each nephron performs filtration, selective reabsorption, and secretion to produce urine.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Excretion and Homeostasis",
    questionText: "Homeostasis refers to the ability of an organism to",
    answerText: "Maintain a stable internal environment despite external changes",
    explanationText: "Homeostasis (e.g. regulation of body temperature, blood glucose, and water balance) keeps internal conditions within narrow optimal ranges.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Excretion and Homeostasis",
    questionText: "Antidiuretic hormone (ADH) acts on the kidney to",
    answerText: "Increase water reabsorption from the collecting duct",
    explanationText: "ADH (vasopressin), released by the pituitary gland, increases the permeability of the collecting duct, causing more water to be reabsorbed and producing concentrated urine.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Excretion and Homeostasis",
    questionText: "Carbon dioxide is excreted from mammals mainly through the",
    answerText: "Lungs",
    explanationText: "CO₂ produced in tissues diffuses into the blood, is transported mainly as bicarbonate ions, and is expired through the lungs.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Excretion and Homeostasis",
    questionText: "The liver plays a role in excretion by",
    answerText: "Converting ammonia to urea (deamination)",
    explanationText: "The liver deaminates excess amino acids, producing ammonia which is immediately converted to urea via the ornithine cycle for safe excretion by the kidneys.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Excretion and Homeostasis",
    questionText: "Sweat glands in the skin help with homeostasis by",
    answerText: "Cooling the body through evaporation of sweat",
    explanationText: "Evaporation of sweat from the skin surface absorbs latent heat, lowering body temperature during overheating.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Excretion and Homeostasis",
    questionText: "Bile pigments, which are excreted by the liver into the bile, are derived from the breakdown of",
    answerText: "Haemoglobin in worn-out red blood cells",
    explanationText: "The liver breaks down old red blood cells; haemoglobin is degraded into bilirubin and biliverdin, which are excreted in bile and give faeces their colour.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Excretion and Homeostasis",
    questionText: "The process in the nephron by which small molecules pass from blood into the Bowman's capsule is called",
    answerText: "Ultrafiltration",
    explanationText: "High blood pressure in the glomerular capillaries forces water, glucose, urea, and salts (but not large proteins or cells) into the Bowman's capsule.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Excretion and Homeostasis",
    questionText: "Which organ in plants is most important for the excretion of excess water vapour?",
    answerText: "Leaf (via stomata)",
    explanationText: "Plants lose excess water vapour mainly through stomata in the leaves during transpiration, which is also a form of excretion of water.",
    difficulty: 2,
    source: PH,
  },
];

// ── 6. Growth, Development and Reproduction ──────────────────────────────────
const growth: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Growth, Development and Reproduction",
    questionText: "Cell division that produces two genetically identical daughter cells is called",
    answerText: "Mitosis",
    explanationText: "Mitosis produces two identical diploid daughter cells and is used for growth, repair, and asexual reproduction. It differs from meiosis which halves chromosome number.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Growth, Development and Reproduction",
    questionText: "The bending of a plant shoot towards a light source is an example of",
    answerText: "Positive phototropism",
    explanationText: "Positive phototropism is caused by unequal distribution of auxin; higher auxin concentration on the shaded side causes faster growth, bending the shoot toward the light.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Growth, Development and Reproduction",
    questionText: "In flowering plants, pollination is defined as the transfer of pollen from an anther to a",
    answerText: "Stigma",
    explanationText: "Pollination is the transfer of pollen grains (containing male gametes) from the anther of a flower to the stigma, which may be of the same or a different flower.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Growth, Development and Reproduction",
    questionText: "The process by which a tadpole transforms into a frog involves dramatic change in body form, a process called",
    answerText: "Metamorphosis",
    explanationText: "Metamorphosis (complete metamorphosis in frogs) involves the larval stage (tadpole) undergoing profound structural changes to become the adult form (frog).",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Growth, Development and Reproduction",
    questionText: "The growth region in plant roots where cells elongate rapidly is called the",
    answerText: "Zone of elongation",
    explanationText: "The zone of elongation lies just above the meristematic zone; cells produced by division here elongate dramatically, pushing the root tip through the soil.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Growth, Development and Reproduction",
    questionText: "Binary fission, budding, and spore formation are all examples of",
    answerText: "Asexual reproduction",
    explanationText: "Asexual reproduction involves only one parent and produces genetically identical offspring (clones). It does not involve gametes or fertilisation.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Growth, Development and Reproduction",
    questionText: "Fertilisation in flowering plants occurs when the pollen tube delivers a male nucleus to the",
    answerText: "Ovule",
    explanationText: "The pollen tube grows down the style and into the ovule. Double fertilisation occurs: one nucleus fuses with the egg cell, the other with polar nuclei to form endosperm.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Growth, Development and Reproduction",
    questionText: "Which hormone controls the female menstrual cycle and is produced by the ovary?",
    answerText: "Oestrogen",
    explanationText: "Oestrogen (produced by follicle cells in the ovary) stimulates thickening of the uterine lining and regulates the menstrual cycle together with progesterone.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Growth, Development and Reproduction",
    questionText: "Seed dispersal by wind is facilitated by seeds or fruits that are",
    answerText: "Light and have wing-like or hair-like structures",
    explanationText: "Wind-dispersed fruits (e.g. sycamore, dandelion) are small, light, and often have wings or feathery parachutes (pappus) that allow them to be carried by air currents.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Growth, Development and Reproduction",
    questionText: "Meiosis is important in sexual reproduction because it",
    answerText: "Halves the chromosome number to produce haploid gametes",
    explanationText: "Meiosis reduces the chromosome number from diploid (2n) to haploid (n). When gametes fuse at fertilisation, the diploid number is restored.",
    difficulty: 2,
    source: PH,
  },
];

// ── 7. Support and Movement ──────────────────────────────────────────────────
const support: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Support and Movement",
    questionText: "The skeleton of insects is an example of an",
    answerText: "Exoskeleton",
    explanationText: "An exoskeleton is a hard outer covering (made of chitin in insects) that provides support and protection. It is shed (moulted) as the animal grows.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Support and Movement",
    questionText: "The main tissue responsible for providing mechanical support in non-woody herbaceous plants is",
    answerText: "Collenchyma",
    explanationText: "Collenchyma cells have unevenly thickened cell walls and provide flexible support in young stems, leaf stalks, and non-woody plants.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Support and Movement",
    questionText: "Muscles are attached to bones by connective tissues called",
    answerText: "Tendons",
    explanationText: "Tendons are strong, inelastic fibrous connective tissue that attach skeletal muscles to bones, transmitting the force of muscle contraction.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Support and Movement",
    questionText: "The hydrostatic skeleton used for movement in earthworms works by",
    answerText: "Fluid pressure transmitted through a fluid-filled body cavity (coelom)",
    explanationText: "Earthworms contract longitudinal or circular muscles against incompressible coelomic fluid, causing segments to shorten-and-widen or lengthen-and-narrow for movement.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Support and Movement",
    questionText: "Bones are connected to other bones at joints by fibrous connective tissues called",
    answerText: "Ligaments",
    explanationText: "Ligaments are slightly elastic fibrous bands that hold bones together at joints, stabilising the skeleton and preventing dislocation.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Support and Movement",
    questionText: "Which type of joint allows the widest range of movement in all directions, such as the shoulder joint?",
    answerText: "Ball-and-socket joint",
    explanationText: "A ball-and-socket joint (e.g. shoulder, hip) allows movement in three planes: flexion/extension, abduction/adduction, and rotation.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Support and Movement",
    questionText: "Turgor pressure in plant cells contributes to support by",
    answerText: "Making cells rigid when water fills the vacuole",
    explanationText: "When the vacuole is full of water, the cytoplasm pushes against the cell wall creating turgor pressure, making herbaceous plants rigid and upright.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Support and Movement",
    questionText: "The type of muscle tissue found in the heart is called",
    answerText: "Cardiac muscle",
    explanationText: "Cardiac muscle is involuntary, striated, and found only in the heart. It contracts rhythmically without fatigue throughout life.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Support and Movement",
    questionText: "An antagonistic pair of muscles works by",
    answerText: "One contracting while the other relaxes to produce movement",
    explanationText: "For example, the biceps and triceps are antagonistic: when the biceps contracts (flexion), the triceps relaxes, and vice versa for extension.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Support and Movement",
    questionText: "The endoskeleton of vertebrates is made primarily of",
    answerText: "Bone and cartilage",
    explanationText: "Vertebrate endoskeletons consist of bone (calcified) and cartilage (flexible). Cartilage is the main skeletal material in sharks and is retained at joint surfaces in bony vertebrates.",
    difficulty: 1,
    source: PH,
  },
];

// ── 8. Coordination and Control ──────────────────────────────────────────────
const coordination: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Coordination and Control",
    questionText: "The part of the brain responsible for coordinating balance and muscle coordination is the",
    answerText: "Cerebellum",
    explanationText: "The cerebellum coordinates voluntary muscle movements, posture, and balance by comparing intended movement with actual movement signals.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Coordination and Control",
    questionText: "A reflex arc differs from a voluntary response in that a reflex arc",
    answerText: "Does not require conscious involvement of the brain",
    explanationText: "Reflex arcs pass through the spinal cord only (receptor → sensory neurone → relay neurone → motor neurone → effector), bypassing the conscious brain for a faster response.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Coordination and Control",
    questionText: "Insulin is secreted by which cells in the pancreas?",
    answerText: "Beta cells of the islets of Langerhans",
    explanationText: "Beta cells in the pancreatic islets of Langerhans secrete insulin in response to high blood glucose, stimulating uptake of glucose by cells.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Coordination and Control",
    questionText: "The chemical messenger released at the synapse between two neurones is called a",
    answerText: "Neurotransmitter",
    explanationText: "Neurotransmitters (e.g. acetylcholine, dopamine) are released from synaptic vesicles into the synaptic cleft, diffuse across, and bind to receptors on the post-synaptic membrane.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Coordination and Control",
    questionText: "The pupillary reflex (constriction of the pupil in bright light) is controlled by the",
    answerText: "Autonomic nervous system",
    explanationText: "The autonomic nervous system (particularly the parasympathetic division) controls involuntary responses such as pupil dilation/constriction and heart rate.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Coordination and Control",
    questionText: "Adrenaline (epinephrine), secreted by the adrenal medulla, prepares the body for",
    answerText: "Fight-or-flight response",
    explanationText: "Adrenaline increases heart rate, dilates airways, mobilises glucose from glycogen stores, and diverts blood to muscles — preparing the body for emergencies.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Coordination and Control",
    questionText: "The part of the eye that contains the light-sensitive receptor cells (rods and cones) is the",
    answerText: "Retina",
    explanationText: "The retina is the innermost layer of the eye. Rods detect light intensity (dim light/monochrome) and cones detect colour (bright light/colour vision).",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Coordination and Control",
    questionText: "Thyroxine, a hormone produced by the thyroid gland, primarily controls",
    answerText: "Metabolic rate",
    explanationText: "Thyroxine (T4) regulates the basal metabolic rate of cells. Deficiency causes hypothyroidism (slow metabolism); excess causes hyperthyroidism.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Coordination and Control",
    questionText: "The receptor cells in the semicircular canals of the ear detect",
    answerText: "Rotational (angular) movement of the head",
    explanationText: "The three semicircular canals, each oriented in a different plane, detect angular acceleration (head rotation) via movement of endolymph fluid over hair cells.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Coordination and Control",
    questionText: "Tropisms in plants are growth responses to directional stimuli, mediated by the plant hormone",
    answerText: "Auxin (IAA)",
    explanationText: "Indole-3-acetic acid (auxin) promotes cell elongation. Unequal auxin distribution in response to directional light or gravity causes differential growth (tropisms).",
    difficulty: 2,
    source: PH,
  },
];

// ── 9. Ecology and the Environment ───────────────────────────────────────────
const ecology: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Ecology and the Environment",
    questionText: "In a food chain, organisms that feed directly on green plants are called",
    answerText: "Primary consumers (herbivores)",
    explanationText: "Primary consumers eat producers (plants). Secondary consumers eat primary consumers, and so on. Energy decreases at each trophic level.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Ecology and the Environment",
    questionText: "The role of decomposers in an ecosystem is to",
    answerText: "Break down dead organic matter and recycle nutrients",
    explanationText: "Decomposers (bacteria and fungi) digest organic matter, releasing inorganic nutrients back into the soil, where they can be absorbed by plants again.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Ecology and the Environment",
    questionText: "The relationship between a tapeworm and its human host is an example of",
    answerText: "Parasitism",
    explanationText: "Parasitism is a relationship where one organism (the parasite) benefits at the expense of the other (the host), which is harmed but usually not immediately killed.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Ecology and the Environment",
    questionText: "The total number of individuals of one species living in a specific area at a given time is called the",
    answerText: "Population",
    explanationText: "A population is all members of the same species in a particular area. Multiple populations of different species together form a community.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Ecology and the Environment",
    questionText: "Which type of pollution is most directly caused by the burning of fossil fuels?",
    answerText: "Air pollution (carbon dioxide, sulphur dioxide, nitrogen oxides)",
    explanationText: "Burning fossil fuels releases CO₂ (greenhouse gas), SO₂ (acid rain), and NOₓ into the atmosphere, causing climate change and respiratory diseases.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Ecology and the Environment",
    questionText: "A relationship in which both organisms benefit is called",
    answerText: "Mutualism",
    explanationText: "Mutualism is a symbiotic relationship where both species benefit (e.g. clownfish and sea anemone; nitrogen-fixing bacteria in legume root nodules).",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Ecology and the Environment",
    questionText: "In an energy pyramid, the greatest amount of energy is found at the",
    answerText: "Producer (first trophic) level",
    explanationText: "Only about 10% of energy is passed from one trophic level to the next; the rest is lost as heat. The producers contain the most total energy in the ecosystem.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Ecology and the Environment",
    questionText: "Malaria is caused by a protozoan parasite transmitted to humans by",
    answerText: "Female Anopheles mosquito",
    explanationText: "The female Anopheles mosquito acts as the vector, injecting Plasmodium sporozoites into the human bloodstream when it takes a blood meal.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Ecology and the Environment",
    questionText: "The process by which nitrogen in the atmosphere is converted to ammonia by bacteria is called",
    answerText: "Nitrogen fixation",
    explanationText: "Nitrogen-fixing bacteria (e.g. Rhizobium in legume root nodules) convert atmospheric N₂ to ammonia (NH₃), making nitrogen available to plants.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Ecology and the Environment",
    questionText: "Eutrophication of water bodies is primarily caused by",
    answerText: "Excess nitrates and phosphates from agricultural fertilisers",
    explanationText: "Run-off of fertilisers causes algal blooms. When algae die, decomposers use up dissolved oxygen, causing aquatic organisms to suffocate.",
    difficulty: 3,
    source: PH,
  },
];

// ── 10. Genetics, Variation and Evolution ────────────────────────────────────
const genetics: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Genetics, Variation and Evolution",
    questionText: "The physical appearance of an organism resulting from its genetic makeup is called its",
    answerText: "Phenotype",
    explanationText: "The phenotype is the observable traits of an organism (e.g. height, eye colour) resulting from interaction between genotype and environment.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Genetics, Variation and Evolution",
    questionText: "If both parents are heterozygous for a trait (Aa × Aa), the expected ratio of dominant to recessive phenotype in offspring is",
    answerText: "3:1",
    explanationText: "A monohybrid cross Aa × Aa gives offspring AA:Aa:aa = 1:2:1 by genotype, but 3 dominant (AA + Aa) : 1 recessive (aa) by phenotype.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Genetics, Variation and Evolution",
    questionText: "The hereditary material that carries genetic information in most organisms is",
    answerText: "DNA (deoxyribonucleic acid)",
    explanationText: "DNA is a double helix of nucleotide bases (A, T, G, C) that stores genetic instructions. It is organised into chromosomes within the cell nucleus.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Genetics, Variation and Evolution",
    questionText: "A sudden heritable change in the DNA sequence of an organism is called a",
    answerText: "Mutation",
    explanationText: "Mutations are permanent changes in base sequences of DNA. They can be spontaneous or induced by mutagens (radiation, certain chemicals) and may be beneficial, neutral, or harmful.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Genetics, Variation and Evolution",
    questionText: "Sickle-cell anaemia is an example of a disease caused by",
    answerText: "A gene mutation (single base substitution)",
    explanationText: "Sickle-cell anaemia results from a single nucleotide substitution (A→T) in the haemoglobin gene, causing glutamic acid to be replaced by valine, altering red blood cell shape.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Genetics, Variation and Evolution",
    questionText: "Continuous variation (e.g. height, skin colour) differs from discontinuous variation in that it is",
    answerText: "Controlled by many genes (polygenic) and strongly influenced by the environment",
    explanationText: "Continuous variation shows a range of phenotypes with no clear categories; it is polygenic and environment-sensitive. Discontinuous variation (e.g. blood group) shows distinct categories.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Genetics, Variation and Evolution",
    questionText: "Charles Darwin's theory of natural selection is based on the idea that organisms with favourable variations are more likely to",
    answerText: "Survive and reproduce, passing traits to offspring",
    explanationText: "Natural selection: heritable variation exists; individuals better adapted to the environment survive and reproduce more; favourable traits increase in frequency over generations.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Genetics, Variation and Evolution",
    questionText: "In humans, sex is determined by",
    answerText: "Sex chromosomes (XX = female; XY = male)",
    explanationText: "Humans have 23 pairs of chromosomes; the 23rd pair are the sex chromosomes. Females are XX and males are XY. The Y chromosome carries the SRY gene that triggers male development.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Genetics, Variation and Evolution",
    questionText: "The evidence for evolution includes all of the following EXCEPT",
    answerText: "The existence of unchanging species over geological time",
    explanationText: "Evidence for evolution includes fossil records, comparative anatomy (homologous structures), comparative biochemistry, biogeography, and direct observation. Species that appear unchanged are the exception, not evidence against evolution.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Genetics, Variation and Evolution",
    questionText: "Organisms that can interbreed and produce fertile offspring are said to belong to the same",
    answerText: "Species",
    explanationText: "The biological species concept defines a species as a group of organisms that can interbreed under natural conditions and produce viable, fertile offspring.",
    difficulty: 1,
    source: PH,
  },
];

export const biologyQuestions: ResolvableQuestion[] = [
  ...cellBiology,
  ...nutrition,
  ...respiration,
  ...transport,
  ...excretion,
  ...growth,
  ...support,
  ...coordination,
  ...ecology,
  ...genetics,
];
