import { Prisma } from "@prisma/client";

type ResolvableQuestion = Omit<
  Prisma.PastQuestionCreateManyInput,
  "subjectId" | "topicId"
> & {
  subjectName: string;
  topicTitle: string;
};

const S = "WAEC Economics";
const PH = "placeholder";

// ── 1. Basic Economic Concepts and Systems ───────────────────────────────────
const basicConcepts: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Basic Economic Concepts and Systems",
    questionText: "The basic economic problem facing every society is",
    answerText: "Scarcity of resources relative to unlimited wants",
    explanationText: "Scarcity exists because human wants are unlimited while the resources (land, labour, capital, enterprise) available to satisfy them are finite.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Basic Economic Concepts and Systems",
    questionText: "The opportunity cost of a decision is best defined as",
    answerText: "The value of the next best alternative forgone",
    explanationText: "When a choice is made, the opportunity cost is what you sacrifice — the best alternative you did not choose. It is the true cost of any economic decision.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Basic Economic Concepts and Systems",
    questionText: "The production possibility curve (PPC) illustrates",
    answerText: "The maximum combinations of two goods an economy can produce with given resources",
    explanationText: "Points on the PPC show efficient production; points inside show under-utilisation; points outside are unattainable. The slope shows opportunity cost.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Basic Economic Concepts and Systems",
    questionText: "In a free-market (capitalist) economy, the basic economic questions of what, how, and for whom to produce are determined by",
    answerText: "The price mechanism (market forces of demand and supply)",
    explanationText: "In capitalism, private individuals own resources and the price mechanism allocates them. Prices signal what consumers want and guide producers' decisions.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Basic Economic Concepts and Systems",
    questionText: "Land as a factor of production includes",
    answerText: "All natural resources including land surface, forests, minerals, and water",
    explanationText: "In economics, 'land' encompasses all gifts of nature — not just agricultural land, but also mineral deposits, water bodies, forests, and the electromagnetic spectrum.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Basic Economic Concepts and Systems",
    questionText: "The branch of economics that studies the behaviour of individual economic units (households and firms) is called",
    answerText: "Microeconomics",
    explanationText: "Microeconomics examines individual markets, firms, and consumers — pricing, production decisions, and resource allocation at the individual level.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Basic Economic Concepts and Systems",
    questionText: "In a mixed economy, economic decisions are made by",
    answerText: "Both the government and private individuals",
    explanationText: "A mixed economy combines elements of free market (private ownership) and command (government planning) systems. Most modern economies are mixed.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Basic Economic Concepts and Systems",
    questionText: "The reward for capital as a factor of production is",
    answerText: "Interest",
    explanationText: "Factors of production earn income: land earns rent, labour earns wages, capital earns interest, and enterprise (entrepreneurship) earns profit.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Basic Economic Concepts and Systems",
    questionText: "Which of the following is classified as a secondary economic activity?",
    answerText: "Manufacturing (converting raw materials into finished goods)",
    explanationText: "Secondary activities involve processing raw materials. Primary activities (farming, mining) extract resources; tertiary activities (services) do not produce physical goods.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Basic Economic Concepts and Systems",
    questionText: "An outward shift of the production possibility curve represents",
    answerText: "Economic growth (increase in productive capacity)",
    explanationText: "The PPC shifts outward when there is an increase in the quantity or quality of resources (e.g. new technology, capital investment, more labour), allowing more of both goods to be produced.",
    difficulty: 2,
    source: PH,
  },
];

// ── 2. Demand, Supply and Price Determination ────────────────────────────────
const demandSupply: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Demand, Supply and Price Determination",
    questionText: "According to the law of demand, as the price of a good rises, ceteris paribus, the quantity demanded",
    answerText: "Decreases",
    explanationText: "The law of demand states an inverse relationship between price and quantity demanded: higher prices make goods less affordable, so consumers buy less.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Demand, Supply and Price Determination",
    questionText: "Price elasticity of demand measures",
    answerText: "The responsiveness of quantity demanded to a change in price",
    explanationText: "PED = (% change in quantity demanded) ÷ (% change in price). |PED| > 1 is elastic; |PED| < 1 is inelastic; |PED| = 1 is unit elastic.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Demand, Supply and Price Determination",
    questionText: "A rightward shift of the supply curve indicates that producers are",
    answerText: "Willing and able to supply more at each price",
    explanationText: "Supply increases (curve shifts right) due to lower production costs, improved technology, more producers, or favourable government policy.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Demand, Supply and Price Determination",
    questionText: "The equilibrium price in a market is determined where",
    answerText: "Quantity demanded equals quantity supplied",
    explanationText: "At equilibrium, there is no shortage or surplus. If price is above equilibrium, surplus causes price to fall; if below, shortage causes price to rise.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Demand, Supply and Price Determination",
    questionText: "If the government sets a maximum price (price ceiling) below the equilibrium price, the result will be",
    answerText: "A shortage (excess demand)",
    explanationText: "A price ceiling below equilibrium reduces quantity supplied and increases quantity demanded, creating persistent excess demand (shortage).",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Demand, Supply and Price Determination",
    questionText: "Two goods are said to be substitutes if the cross-price elasticity of demand between them is",
    answerText: "Positive",
    explanationText: "Positive cross-price elasticity means a rise in the price of Good A increases demand for Good B (they are substitutes, e.g. butter and margarine).",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Demand, Supply and Price Determination",
    questionText: "The demand for petrol is likely to be price inelastic because",
    answerText: "It has few close substitutes and is a necessity for many users",
    explanationText: "Goods with few substitutes, that form a small proportion of income, or are necessities tend to have inelastic demand — consumers continue buying despite price rises.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Demand, Supply and Price Determination",
    questionText: "An increase in consumer income will cause the demand curve for a normal good to",
    answerText: "Shift rightward (increase)",
    explanationText: "For normal goods, demand rises with income. The curve shifts right — consumers buy more at every price level. For inferior goods, the effect is reversed.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Demand, Supply and Price Determination",
    questionText: "A government-imposed minimum price (price floor) set above the equilibrium price will result in",
    answerText: "A surplus (excess supply)",
    explanationText: "A price floor above equilibrium raises quantity supplied but reduces quantity demanded, creating a persistent surplus. Examples: minimum wage, agricultural price supports.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Demand, Supply and Price Determination",
    questionText: "Income elasticity of demand for an inferior good is",
    answerText: "Negative",
    explanationText: "For inferior goods (e.g. low-quality staples), demand falls as income rises, giving a negative income elasticity. Normal goods have positive income elasticity.",
    difficulty: 2,
    source: PH,
  },
];

// ── 3. Theory of Consumer Behaviour ──────────────────────────────────────────
const consumerBehaviour: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Theory of Consumer Behaviour",
    questionText: "Total utility is maximised when",
    answerText: "Marginal utility equals zero",
    explanationText: "Total utility reaches its maximum when consuming one more unit adds nothing — i.e., marginal utility (MU) is zero. Consuming beyond this point decreases total utility.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Consumer Behaviour",
    questionText: "The law of diminishing marginal utility states that as a consumer consumes more units of a good, ceteris paribus,",
    answerText: "Each additional unit gives less additional satisfaction",
    explanationText: "Marginal utility (extra satisfaction from one more unit) declines as consumption increases. This explains the downward-sloping demand curve.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Consumer Behaviour",
    questionText: "A consumer is in equilibrium when the marginal utility per naira spent on each good is",
    answerText: "Equal across all goods consumed",
    explanationText: "Consumer equilibrium: MU_A/P_A = MU_B/P_B = ... = MU/P for all goods. If these are unequal, the consumer can reallocate spending to increase total utility.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Consumer Behaviour",
    questionText: "The difference between what a consumer is willing to pay for a good and what they actually pay is called",
    answerText: "Consumer surplus",
    explanationText: "Consumer surplus measures the net benefit to consumers. If the market price is ₦500 but you would have paid ₦800, your consumer surplus is ₦300.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Consumer Behaviour",
    questionText: "Utility in economics refers to",
    answerText: "The satisfaction or benefit derived from consuming a good or service",
    explanationText: "Utility is a measure of the subjective satisfaction a consumer gets from consuming a product. It is measured in hypothetical units called 'utils'.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Consumer Behaviour",
    questionText: "When a consumer's income is fully spent and total utility is maximised, the consumer is said to be in",
    answerText: "Consumer equilibrium",
    explanationText: "At consumer equilibrium, the consumer allocates their budget to maximise total utility. Changing the allocation would decrease total satisfaction.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Consumer Behaviour",
    questionText: "Which of the following would cause a consumer's demand curve for a good to shift leftward?",
    answerText: "A fall in consumer income (for a normal good)",
    explanationText: "For normal goods, lower income reduces purchasing power, shifting demand left. Other causes include a fall in the price of substitutes or a change in tastes away from the good.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Consumer Behaviour",
    questionText: "If marginal utility is negative, consuming more of the good will",
    answerText: "Decrease total utility",
    explanationText: "Negative MU means additional units reduce total satisfaction. This occurs when a good has been consumed beyond its satiation point (e.g. eating too much).",
    difficulty: 2,
    source: PH,
  },
];

// ── 4. Theory of Production, Cost and Revenue ────────────────────────────────
const production: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Theory of Production, Cost and Revenue",
    questionText: "The law of variable proportions states that as more units of a variable factor are added to fixed factors, beyond a point, the marginal product will",
    answerText: "Diminish",
    explanationText: "Initially output rises rapidly, then more slowly, then can fall. This diminishing marginal returns occurs because fixed factors become over-utilised relative to the variable factor.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Production, Cost and Revenue",
    questionText: "Fixed costs are costs that",
    answerText: "Do not change with the level of output in the short run",
    explanationText: "Fixed costs (e.g. rent, salaries of permanent staff, insurance) must be paid regardless of output. They only change in the long run when all factors become variable.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Production, Cost and Revenue",
    questionText: "Average total cost (ATC) is calculated as",
    answerText: "Total cost divided by output (TC ÷ Q)",
    explanationText: "ATC = TC/Q = AFC + AVC. The ATC curve is U-shaped: initially falls due to spreading fixed costs and rising marginal product, then rises as diminishing returns set in.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Production, Cost and Revenue",
    questionText: "Economies of scale refer to the",
    answerText: "Reduction in long-run average cost as output increases",
    explanationText: "Internal economies of scale (technical, managerial, financial, marketing) reduce LRAC as a firm grows. Diseconomies of scale occur when LRAC rises with further expansion.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Production, Cost and Revenue",
    questionText: "A firm maximises profit when",
    answerText: "Marginal cost equals marginal revenue (MC = MR)",
    explanationText: "Profit maximisation: if MR > MC, producing more adds to profit; if MC > MR, it reduces profit. The optimal output is where MC = MR.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Production, Cost and Revenue",
    questionText: "Division of labour increases productivity mainly because it allows",
    answerText: "Workers to specialise in tasks they perform best",
    explanationText: "Division of labour (breaking production into specialised tasks) increases output through specialisation, skill development, time saving, and use of machinery.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Production, Cost and Revenue",
    questionText: "In the short run, a firm should continue to produce as long as",
    answerText: "Price (average revenue) is at least as high as average variable cost",
    explanationText: "A firm should shut down in the short run only if price falls below AVC. If P ≥ AVC, continuing production covers variable costs and contributes to fixed costs.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Production, Cost and Revenue",
    questionText: "Total revenue minus total cost equals",
    answerText: "Profit (or loss if negative)",
    explanationText: "Profit = TR - TC. When TR > TC the firm makes a profit; when TC > TR it makes a loss; when TR = TC it breaks even (normal profit only).",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Production, Cost and Revenue",
    questionText: "The concept of 'normal profit' in economics represents",
    answerText: "The minimum return needed to keep a firm in its current industry",
    explanationText: "Normal profit is the opportunity cost of the entrepreneur's resources — the minimum needed to prevent them from moving to a different industry. It is included in economic costs.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Theory of Production, Cost and Revenue",
    questionText: "In the long run, all factors of production are",
    answerText: "Variable",
    explanationText: "The distinction between fixed and variable factors applies only in the short run. In the long run, a firm can adjust all inputs — including plant size — making all costs variable.",
    difficulty: 1,
    source: PH,
  },
];

// ── 5. Market Structures ─────────────────────────────────────────────────────
const marketStructures: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Market Structures",
    questionText: "In a perfectly competitive market, individual firms are price-takers because",
    answerText: "Each firm is too small to influence the market price",
    explanationText: "With many small firms selling identical products, no single firm has market power. Each accepts the price set by market supply and demand — it faces a perfectly elastic demand curve.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Market Structures",
    questionText: "A monopolist maximises profit by producing where MC = MR and charges a price that is",
    answerText: "Above marginal cost",
    explanationText: "A monopolist has market power to set price above MC. This results in allocative inefficiency (welfare loss) compared to perfect competition where P = MC.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Market Structures",
    questionText: "Monopolistic competition differs from perfect competition mainly in that firms in monopolistic competition",
    answerText: "Sell differentiated (not identical) products",
    explanationText: "Product differentiation (branding, quality, location) gives monopolistically competitive firms some price-setting power, unlike perfect competition where products are homogeneous.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Market Structures",
    questionText: "A natural monopoly arises when",
    answerText: "A single firm can supply the entire market at a lower cost than multiple firms",
    explanationText: "Natural monopolies occur in industries with very high fixed costs and economies of scale (e.g. utilities, railways). Duplicating infrastructure would raise costs.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Market Structures",
    questionText: "Price discrimination (charging different prices to different consumers for the same product) is possible only when",
    answerText: "Markets can be separated and resale between groups is prevented",
    explanationText: "For price discrimination to work: markets must be separable (e.g. by geography, age, time), the firm must have price-setting power, and resale (arbitrage) must be prevented.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Market Structures",
    questionText: "An oligopoly is a market structure characterised by",
    answerText: "A few large firms that are mutually interdependent",
    explanationText: "In an oligopoly (e.g. Nigeria's telecommunications market), each firm must consider how rivals will react to its pricing and output decisions — strategic interdependence.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Market Structures",
    questionText: "In perfect competition, long-run equilibrium is reached when firms earn",
    answerText: "Only normal profit (zero economic profit)",
    explanationText: "Supernormal profit attracts new entrants (no barriers to entry), increasing supply and reducing price until only normal profit remains. Losses cause exit until normal profit is restored.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Market Structures",
    questionText: "A cartel is an example of which market behaviour?",
    answerText: "Collusion among oligopolists to fix prices",
    explanationText: "A cartel is a formal agreement among competing firms (oligopolists) to restrict output and fix prices to maximise collective profit, behaving like a monopoly. OPEC is an example.",
    difficulty: 2,
    source: PH,
  },
];

// ── 6. Business Organisations and Distributive Trade ─────────────────────────
const businessOrgs: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Business Organisations and Distributive Trade",
    questionText: "The main advantage of a public limited company over a sole proprietorship is",
    answerText: "Limited liability for shareholders",
    explanationText: "In a public limited company (PLC), shareholders' liability is limited to the amount they invested. Sole proprietors have unlimited liability — personal assets can be seized to pay debts.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Business Organisations and Distributive Trade",
    questionText: "A cooperative society is primarily formed to",
    answerText: "Provide mutual economic benefit for its members",
    explanationText: "Cooperatives (e.g. farmers' cooperatives, credit unions) are member-owned organisations that pool resources, reduce costs, and share profits among members.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Business Organisations and Distributive Trade",
    questionText: "Privatisation refers to the transfer of ownership of businesses from",
    answerText: "Government (public sector) to private individuals or companies",
    explanationText: "Privatisation is a policy of selling state-owned enterprises to the private sector to improve efficiency, reduce government spending, and encourage competition.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Business Organisations and Distributive Trade",
    questionText: "In a partnership, the partners who take part in management but whose liability is limited are called",
    answerText: "Limited partners",
    explanationText: "A limited partnership has at least one general partner (unlimited liability, manages the business) and limited partners (liable only up to their investment, cannot manage).",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Business Organisations and Distributive Trade",
    questionText: "A retailer differs from a wholesaler in that a retailer sells goods",
    answerText: "Directly to the final consumer in small quantities",
    explanationText: "The distribution channel is: producer → wholesaler (buys in bulk) → retailer (sells in small quantities to consumers) → consumer.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Business Organisations and Distributive Trade",
    questionText: "The main source of finance for a public limited company is",
    answerText: "Selling shares to the public on the stock exchange",
    explanationText: "PLCs can raise large amounts of capital by issuing shares to the public through a stock exchange (IPO). This distinguishes them from private limited companies.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Business Organisations and Distributive Trade",
    questionText: "The disadvantage of a sole proprietorship is",
    answerText: "Unlimited personal liability for business debts",
    explanationText: "A sole trader owns all assets and keeps all profits, but also bears all risks. Personal assets (home, savings) can be seized to settle business debts.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Business Organisations and Distributive Trade",
    questionText: "A multinational corporation (MNC) is a company that",
    answerText: "Operates in more than one country with headquarters in the home country",
    explanationText: "MNCs (e.g. Shell, Nestlé, MTN) have subsidiaries or branches in many countries, enabling them to exploit global markets, lower costs, and access resources.",
    difficulty: 1,
    source: PH,
  },
];

// ── 7. Population and the Labour Market ──────────────────────────────────────
const population: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Population and the Labour Market",
    questionText: "According to Malthus's theory of population, population grows geometrically while food supply grows",
    answerText: "Arithmetically",
    explanationText: "Malthus argued population doubles (1,2,4,8...) while food supply increases by constant additions (1,2,3,4...). He predicted population would always outgrow food supply, causing famine.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Population and the Labour Market",
    questionText: "An optimum population is defined as the population size that",
    answerText: "Maximises the output per head with given resources and technology",
    explanationText: "Optimum population produces the highest per capita income. A population above optimum means diminishing returns; below optimum means under-utilisation of resources.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Population and the Labour Market",
    questionText: "Structural unemployment occurs when",
    answerText: "Workers' skills no longer match the requirements of available jobs",
    explanationText: "Structural unemployment results from shifts in the economy (e.g. automation, industrial decline) making certain skills obsolete. Retraining is the long-term solution.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Population and the Labour Market",
    questionText: "The wage rate in a perfectly competitive labour market is determined by",
    answerText: "The intersection of labour demand and labour supply",
    explanationText: "Firms demand labour (downward sloping — diminishing marginal product) and workers supply labour (upward sloping). The equilibrium wage equates quantity demanded and supplied.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Population and the Labour Market",
    questionText: "A trade union seeks to improve members' wages and conditions mainly through",
    answerText: "Collective bargaining",
    explanationText: "Trade unions negotiate on behalf of all members as a group (collective bargaining), giving workers greater bargaining power than individuals have alone.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Population and the Labour Market",
    questionText: "Nigeria's high dependency ratio means that",
    answerText: "A large proportion of the population is economically inactive (young or old) relative to those of working age",
    explanationText: "Dependency ratio = (dependants ÷ working-age population) × 100. A high ratio puts pressure on working adults to support non-workers, limiting savings and investment.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Population and the Labour Market",
    questionText: "Frictional unemployment refers to the unemployment that arises from",
    answerText: "Workers temporarily between jobs while searching for new employment",
    explanationText: "Frictional unemployment is short-term and voluntary — workers leave one job and take time to find another. It exists even in a healthy economy and is considered normal.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Population and the Labour Market",
    questionText: "The labour force of a country consists of",
    answerText: "All employed and unemployed persons of working age who are willing and able to work",
    explanationText: "The labour force (economically active population) excludes those outside working age, full-time students, retirees, and those unwilling to work.",
    difficulty: 1,
    source: PH,
  },
];

// ── 8. Agriculture and Industrialisation ─────────────────────────────────────
const agriculture: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Agriculture and Industrialisation",
    questionText: "Subsistence farming differs from commercial farming in that subsistence farming",
    answerText: "Produces mainly for the farmer's own consumption, not for sale",
    explanationText: "Subsistence farmers grow just enough to feed themselves and their family. Commercial farming produces crops or livestock primarily for sale and profit.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Agriculture and Industrialisation",
    questionText: "The concept of 'agro-allied industries' refers to industries that",
    answerText: "Process or use agricultural products as raw materials",
    explanationText: "Agro-allied (agro-industrial) industries (e.g. textile mills, flour mills, palm oil processing) depend on agriculture for inputs and help add value to agricultural output.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Agriculture and Industrialisation",
    questionText: "A major constraint to agricultural development in Nigeria is",
    answerText: "Inadequate infrastructure (poor roads, storage facilities, irrigation)",
    explanationText: "Limited rural roads, storage, irrigation, and access to credit prevent Nigerian farmers from increasing productivity and reaching markets — key constraints to agricultural development.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Agriculture and Industrialisation",
    questionText: "Import substitution industrialisation (ISI) is a strategy in which a country",
    answerText: "Develops domestic industries to produce goods previously imported",
    explanationText: "ISI uses tariffs and subsidies to protect infant domestic industries and reduce dependence on imports, aiming to diversify the economy and create employment.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Agriculture and Industrialisation",
    questionText: "The Malthusian food trap suggests that improvements in agricultural productivity will ultimately be",
    answerText: "Offset by population growth",
    explanationText: "Malthus argued that any rise in food production encourages population growth, which eventually returns living standards to subsistence level — the 'population trap'.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Agriculture and Industrialisation",
    questionText: "Cottage (small-scale) industries are typically characterised by",
    answerText: "Production using simple tools, low capital, and family or local labour",
    explanationText: "Cottage industries (e.g. weaving, pottery, soap-making) operate at household level with minimal capital. They are important in developing economies for rural employment.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Agriculture and Industrialisation",
    questionText: "The Green Revolution refers to the dramatic increase in food production through",
    answerText: "High-yielding crop varieties, fertilisers, irrigation, and mechanisation",
    explanationText: "The Green Revolution (1960s–1970s) introduced improved seed varieties, chemical fertilisers, and modern farming techniques, significantly increasing global crop yields.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Agriculture and Industrialisation",
    questionText: "Industrial location near raw material sources is most important for industries that are",
    answerText: "Weight-losing (where raw materials weigh more than the finished product)",
    explanationText: "Weight-losing industries (e.g. iron smelting, sugar refining) locate near raw materials to minimise transport costs. Weight-gaining industries locate near markets.",
    difficulty: 3,
    source: PH,
  },
];

// ── 9. Money, Banking and Inflation ──────────────────────────────────────────
const money: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Money, Banking and Inflation",
    questionText: "The primary function of money is to serve as a",
    answerText: "Medium of exchange",
    explanationText: "Money's primary function is to facilitate exchange, overcoming the double coincidence of wants problem in barter. Other functions include store of value, unit of account, and standard of deferred payment.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Money, Banking and Inflation",
    questionText: "Demand-pull inflation occurs when",
    answerText: "Aggregate demand exceeds aggregate supply (too much money chasing too few goods)",
    explanationText: "Demand-pull inflation is caused by excessive demand in the economy, often from increased money supply, government spending, or credit expansion.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Money, Banking and Inflation",
    questionText: "The central bank controls money supply mainly through",
    answerText: "Open market operations, reserve requirements, and the discount rate",
    explanationText: "Monetary policy tools: OMO (buying/selling government bonds), changing cash reserve ratios, and adjusting the discount/lending rate to commercial banks.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Money, Banking and Inflation",
    questionText: "Cost-push inflation is caused by",
    answerText: "Rising production costs (wages, raw materials) that firms pass on as higher prices",
    explanationText: "Cost-push inflation originates from the supply side — higher wages, raw material costs (e.g. oil price shocks), or import prices push up production costs and prices.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Money, Banking and Inflation",
    questionText: "The money multiplier describes how an initial bank deposit",
    answerText: "Creates a multiple expansion of credit in the banking system",
    explanationText: "Banks hold only a fraction of deposits as reserves and lend the rest. Each loan becomes a new deposit, creating more loans. Money multiplier = 1 ÷ reserve ratio.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Money, Banking and Inflation",
    questionText: "The main function of a commercial bank that distinguishes it from other financial institutions is",
    answerText: "Accepting deposits and making loans (credit creation)",
    explanationText: "Commercial banks accept deposits from customers, extend credit (loans), and operate the payments system. Credit creation is their defining function, regulated by the central bank.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Money, Banking and Inflation",
    questionText: "Hyperinflation is characterised by",
    answerText: "Extremely rapid and uncontrolled price increases (typically over 50% per month)",
    explanationText: "Hyperinflation destroys the value of money, erodes savings, and destabilises the economy. It is usually caused by excessive money printing to finance government deficits.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Money, Banking and Inflation",
    questionText: "The capital market is distinguished from the money market in that the capital market deals with",
    answerText: "Long-term financial instruments (bonds, shares) with maturities over one year",
    explanationText: "The money market deals with short-term borrowing/lending (under 1 year — Treasury bills, commercial paper). The capital market handles long-term finance (shares, bonds).",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Money, Banking and Inflation",
    questionText: "A development bank (like the Bank of Industry in Nigeria) primarily provides",
    answerText: "Long-term credit to priority sectors for development purposes",
    explanationText: "Development banks finance projects in key sectors (agriculture, industry, infrastructure) with long-term, low-interest loans that commercial banks typically avoid.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Money, Banking and Inflation",
    questionText: "The barter system was replaced by money mainly because barter",
    answerText: "Requires a double coincidence of wants",
    explanationText: "Barter requires that each party wants exactly what the other has — a double coincidence of wants — making complex economies impossible. Money eliminates this constraint.",
    difficulty: 1,
    source: PH,
  },
];

// ── 10. Public Finance and Taxation ──────────────────────────────────────────
const publicFinance: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "Public Finance and Taxation",
    questionText: "A progressive tax is one in which the average tax rate",
    answerText: "Increases as income increases",
    explanationText: "In a progressive tax system (e.g. personal income tax), higher earners pay a higher percentage of their income in tax than lower earners.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Public Finance and Taxation",
    questionText: "Value Added Tax (VAT) is an example of",
    answerText: "An indirect tax",
    explanationText: "Indirect taxes are levied on goods and services, not directly on income. VAT is collected by sellers at each stage of production and ultimately paid by the final consumer.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Public Finance and Taxation",
    questionText: "A balanced budget occurs when government",
    answerText: "Total expenditure equals total revenue",
    explanationText: "A balanced budget: Revenue = Expenditure. A budget deficit (expenditure > revenue) is financed by borrowing. A surplus (revenue > expenditure) can reduce national debt.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Public Finance and Taxation",
    questionText: "Which principle of taxation states that taxes should be proportional to taxpayers' ability to pay?",
    answerText: "The ability-to-pay principle",
    explanationText: "The ability-to-pay principle (equity) holds that those with greater income or wealth should contribute more in taxes. It is the basis for progressive taxation.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Public Finance and Taxation",
    questionText: "Transfer payments by the government (e.g. social security benefits) are NOT included in GDP calculations because",
    answerText: "They do not represent payment for current productive activity",
    explanationText: "Transfer payments redistribute income (pensions, welfare) without a corresponding production of goods or services, so they do not count as part of GDP.",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Public Finance and Taxation",
    questionText: "The national debt refers to",
    answerText: "The total accumulated borrowings of the government",
    explanationText: "The national debt is the total stock of government borrowings (bonds, treasury bills, foreign loans) that have accumulated over time. It is serviced through interest payments.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Public Finance and Taxation",
    questionText: "Fiscal policy refers to the use of",
    answerText: "Government expenditure and taxation to manage aggregate demand",
    explanationText: "Fiscal policy (budget policy) adjusts spending and taxes to achieve macroeconomic goals — controlling inflation, stimulating growth, and reducing unemployment.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "Public Finance and Taxation",
    questionText: "The Laffer curve illustrates the relationship between tax rates and",
    answerText: "Government tax revenue",
    explanationText: "The Laffer curve shows that both a 0% and 100% tax rate yield zero revenue. There is an optimal rate that maximises revenue; above it, higher taxes reduce revenue by discouraging activity.",
    difficulty: 3,
    source: PH,
  },
];

// ── 11. National Income and Economic Development ──────────────────────────────
const nationalIncome: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "National Income and Economic Development",
    questionText: "Gross Domestic Product (GDP) measures",
    answerText: "The total value of all goods and services produced within a country in a given period",
    explanationText: "GDP counts output regardless of who owns the factors of production. Gross National Product (GNP) adds net factor income from abroad (GNP = GDP + net income from abroad).",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "National Income and Economic Development",
    questionText: "The expenditure approach to measuring national income calculates GDP as",
    answerText: "C + I + G + (X − M)",
    explanationText: "GDP (expenditure) = Consumption + Investment + Government spending + Net exports. This equals total spending on final goods produced in the economy.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "National Income and Economic Development",
    questionText: "Economic growth differs from economic development in that economic development",
    answerText: "Involves improvement in living standards, equity, and quality of life, not just output growth",
    explanationText: "Growth is measured by GDP/GNP increases. Development is broader: it includes poverty reduction, education, health, and quality of life — reflected in the Human Development Index.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "National Income and Economic Development",
    questionText: "Net National Product (NNP) is obtained by subtracting from GNP the amount of",
    answerText: "Capital depreciation (consumption of fixed capital)",
    explanationText: "NNP = GNP − Capital Depreciation. It accounts for the wearing out of capital stock during production, giving a net measure of a country's productive output.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "National Income and Economic Development",
    questionText: "Double counting is avoided in national income accounting by measuring",
    answerText: "Only the value added at each stage of production",
    explanationText: "Value added = output value minus the cost of intermediate inputs. Summing value added at each stage (or counting only final goods) prevents double counting of intermediate products.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "National Income and Economic Development",
    questionText: "The multiplier effect in macroeconomics describes how",
    answerText: "An initial increase in expenditure leads to a larger increase in national income",
    explanationText: "When spending increases by ₦1, income rises by more than ₦1 because each round of spending becomes someone else's income, which is partly re-spent. Multiplier = 1 ÷ (1 − MPC).",
    difficulty: 3,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "National Income and Economic Development",
    questionText: "A major limitation of using GDP per capita as a measure of welfare is that",
    answerText: "It does not show the distribution of income within the population",
    explanationText: "High GDP per capita can coexist with extreme inequality. It also ignores non-monetary welfare (leisure, environment, informal activity) and quality of public services.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "National Income and Economic Development",
    questionText: "Development planning in Nigeria has historically taken the form of",
    answerText: "National development plans (e.g. the National Development Plan, Vision 2020)",
    explanationText: "Nigeria has used successive national development plans since independence to set targets for economic growth, infrastructure development, and diversification from oil dependence.",
    difficulty: 2,
    source: PH,
  },
];

// ── 12. International Trade and Economic Integration ─────────────────────────
const internationalTrade: ResolvableQuestion[] = [
  {
    subjectName: S,
    topicTitle: "International Trade and Economic Integration",
    questionText: "The principle of comparative advantage states that a country should specialise in producing goods in which it has",
    answerText: "The lowest opportunity cost relative to other countries",
    explanationText: "Even if one country is absolutely better at producing everything, both countries gain by specialising where their relative efficiency is greatest and trading.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "International Trade and Economic Integration",
    questionText: "A tariff is",
    answerText: "A tax imposed on imported goods",
    explanationText: "Tariffs raise the price of imports, protect domestic industries, and generate government revenue. They are a trade barrier that reduces import volumes.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "International Trade and Economic Integration",
    questionText: "A favourable balance of trade (trade surplus) means that a country's",
    answerText: "Exports exceed imports in value",
    explanationText: "Trade balance = Exports − Imports. A surplus (X > M) contributes positively to the current account. A deficit means the country imports more than it exports.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "International Trade and Economic Integration",
    questionText: "The balance of payments records",
    answerText: "All economic transactions between a country's residents and the rest of the world",
    explanationText: "The balance of payments has three accounts: current account (trade, income, transfers), capital account, and financial account. The total must balance to zero.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "International Trade and Economic Integration",
    questionText: "The Economic Community of West African States (ECOWAS) was established primarily to",
    answerText: "Promote economic integration and free trade among West African nations",
    explanationText: "ECOWAS (formed 1975, Lagos Treaty) aims to create a common market among its 15 member states, promote free movement of goods, services, capital, and people.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "International Trade and Economic Integration",
    questionText: "The International Monetary Fund (IMF) was primarily established to",
    answerText: "Promote monetary cooperation and provide short-term financial assistance to countries with balance of payments difficulties",
    explanationText: "The IMF (Bretton Woods, 1944) monitors global economic stability, provides emergency loans, and offers policy advice to member countries facing financial crises.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "International Trade and Economic Integration",
    questionText: "OPEC is an example of an international organisation whose main purpose is to",
    answerText: "Coordinate petroleum production and pricing among member countries",
    explanationText: "OPEC (Organisation of the Petroleum Exporting Countries, formed 1960) acts as a cartel, setting production quotas to stabilise and raise oil prices for its members.",
    difficulty: 1,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "International Trade and Economic Integration",
    questionText: "Terms of trade are defined as",
    answerText: "The ratio of export prices to import prices (price of exports ÷ price of imports × 100)",
    explanationText: "A rise in the terms of trade (favourable movement) means a country's exports buy more imports — it can import more goods for the same volume of exports.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "International Trade and Economic Integration",
    questionText: "Import quotas differ from tariffs in that import quotas",
    answerText: "Directly limit the quantity of imports allowed, regardless of price",
    explanationText: "A quota sets an absolute limit on import volume, generating no government revenue. A tariff raises the price of imports, letting market forces determine quantity but earning revenue.",
    difficulty: 2,
    source: PH,
  },
  {
    subjectName: S,
    topicTitle: "International Trade and Economic Integration",
    questionText: "The African Development Bank (AfDB) primarily supports",
    answerText: "Economic and social development projects across African countries",
    explanationText: "The AfDB (established 1964, headquartered in Abidjan/Côte d'Ivoire) provides loans, grants, and technical assistance to African nations for infrastructure and development projects.",
    difficulty: 2,
    source: PH,
  },
];

export const economicsQuestions: ResolvableQuestion[] = [
  ...basicConcepts,
  ...demandSupply,
  ...consumerBehaviour,
  ...production,
  ...marketStructures,
  ...businessOrgs,
  ...population,
  ...agriculture,
  ...money,
  ...publicFinance,
  ...nationalIncome,
  ...internationalTrade,
];
