export type TopicSeed = { title: string; sortOrder: number };

export const topicsBySubject: Record<string, TopicSeed[]> = {
  "SAT Math": [
    { title: "Heart of Algebra", sortOrder: 0 },
    { title: "Systems of linear equations & graphs", sortOrder: 1 },
    { title: "Problem Solving & Data Analysis", sortOrder: 2 },
    { title: "Ratios, rates, and proportional relationships", sortOrder: 3 },
    { title: "Passport to Advanced Math", sortOrder: 4 },
    { title: "Nonlinear expressions & quadratics", sortOrder: 5 },
    { title: "Geometry & Trigonometry", sortOrder: 6 },
    { title: "Circles, area, and volume", sortOrder: 7 },
    { title: "Right triangles & basic trigonometry", sortOrder: 8 },
    { title: "Complex numbers & advanced topics", sortOrder: 9 },
  ],
  "SAT Reading": [
    { title: "Information & Ideas", sortOrder: 0 },
    { title: "Craft & Structure", sortOrder: 1 },
    { title: "Expression of Ideas", sortOrder: 2 },
    { title: "Command of evidence — textual", sortOrder: 3 },
    { title: "Command of evidence — quantitative", sortOrder: 4 },
    { title: "Cross-text connections", sortOrder: 5 },
    { title: "Structure, purpose, and viewpoint", sortOrder: 6 },
    { title: "Vocabulary in context", sortOrder: 7 },
    { title: "Inference and implicit meaning", sortOrder: 8 },
    { title: "Synthesis across texts", sortOrder: 9 },
  ],
  "SAT Writing & Language": [
    { title: "Standard English Conventions", sortOrder: 0 },
    { title: "Sentence Structure", sortOrder: 1 },
    { title: "Verb Tense & Agreement", sortOrder: 2 },
    { title: "Rhetorical Skills", sortOrder: 3 },
    { title: "Punctuation & sentence boundaries", sortOrder: 4 },
    { title: "Agreement, pronouns, & clarity", sortOrder: 5 },
    { title: "Modifiers & parallel structure", sortOrder: 6 },
    { title: "Word choice & concision", sortOrder: 7 },
    { title: "Logical transitions & flow", sortOrder: 8 },
    { title: "Organization & rhetorical goal", sortOrder: 9 },
  ],
};
